// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zglmcmugcxnwkurnknwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnbG1jbXVnY3hud2t1cm5rbndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTc3MzksImV4cCI6MjA2MDQzMzczOX0.oK6RNVch3Q2pPxgll8bYzMBVidsteD7PaZn6Q-dmLS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);